### ISSUE TITLE
Add option to remove transitions during reviews

### ISSUE THREAD

**Issue by slice** [Lemmmy/KanjiSchool#6]
This might be a bit of a niche feature, but I think an option to disable transitions during reviews would be useful. While it's not the end of the world, I do consider them to be a little distracting at times. After having used the [WaniKani lightning mode userscript](https://community.wanikani.com/t/userscript-double-check-version-2x/31456), I've found that I prefer to review subjects without that minuscule amount of motion, as it feels more comfortable for my brain. It's slightly less mental work to visually process the movement, as small as that may seem. I think that it also makes the overall session feel "faster", as progress from one card to the next is literally instant.

Hopefully this feature request doesn't sound too nitpicky, but I'd definitely benefit from this seeing as I sit down and use KanjiSchool for at least an hour every day.

This feature can also be automatically enabled by default if the user has [reduced motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) enabled, which is good for accessibility, although I haven't checked if KanjiSchool has any support for this already.

I might take a shot at implementing this eventually if I find the mental energy to do so. I think this block of code is responsible for the transition during reviews, but I haven't actually verified: https://github.com/Lemmmy/KanjiSchool/blob/c54a4e96108cebc241894bbc8fcacaf85ceb8c74/src/pages/session/SessionQuestionContents.tsx#L41

**Comment by Lemmmy** [comment]
Great suggestion, this would be a brilliant accessibility feature. Thanks for taking a look at the CSS properties and relevant code. Looks like it can also be [queried from JavaScript](https://web.dev/prefers-reduced-motion/#working-with-the-media-query-from-css-and-javascript-contexts) too which would help with the CSSTransition components. I will try to implement this today!

**Comment by Lemmmy** [comment]
I've made an initial pass on this. Currently, it only affects the transitions during lessons and reviews, and the review progress bar animation. 

It will automatically apply if your browser/system is set to prefer reduced motion, or it can be turned on manually with the setting Display settings -> Accessibility -> Prefer reduced motion:
![image](https://user-images.githubusercontent.com/858456/195686352-8080bb02-65eb-4ba3-ab15-abd335dc7d51.png)

You may also find the "Shake the subject characters on an incorrect answer" setting helpful:
![image](https://user-images.githubusercontent.com/858456/195686590-76f1de3c-d5c3-40bb-82c0-a83b905659dc.png)

There are still a few small hiccups to iron out, for example on some systems there is a one-frame flicker between questions, though that is partially due to the way fonts are loaded. Let me know what you think!

**Comment by slice** [comment]
Awesome, thank you so much! I appreciate the incredibly short turnaround for this feature request. 💕 

I was actually in the middle of my morning reviews when you finished this up. I'm using it now and it's great.
