### ISSUE TITLE
Syncing reviews stuck and frequent connection errors

### ISSUE THREAD

**Issue by MartiiDev** [Lemmmy/KanjiSchool#7]
Hey! First of all I love your app and there is no big problem preventing me from using it.

The first thing is only a visual annoyance, the syncing reviews process seem to be stuck at 4000/4391 (I have no idea what those numbers are since I've never had so much reviews). Yesterday it was stuck at exactly 3000 the whole day.
![image](https://user-images.githubusercontent.com/44440955/204670097-6382f6be-99b8-441c-80ac-3edb0fffc5e9.png)

Another issue quite annoying but which doesn't seem to impact the usability is that it very often gives me notifications saying "unable to connect" (or something like that), even though my Internet connection has no problem.

And one final thing, in the devtools console I get:
`sentry.lemmmy.pw/api/5/envelope/?sentry_key=99545754915c403682949277e401d606&sentry_version=7:1
Failed to load resource: net::ERR_NAME_NOT_RESOLVED`
and a lot of:
`Error: timeout of 60000ms exceeded`

These won't prevent me from using your app but I guess it's good to let you know!

**Comment by Lemmmy** [comment]
Hi, thank you very much for the feedback!

The 4000/4391 reviews issue are something I've bumped into as well. It's caused by hitting the WaniKani rate limits. Sometimes KanjiSchool can accidentally make the same request two or three times in a row, and when you combine that with doing a long review session or having to check a lot of reviews (and subjects, progressions, etc.) at the start of the day, the limits can be hit. Currently KanjiSchool does not handle this very well, there's lots of room for improvement there!

One possible workaround if it gets stuck is to wait for a few minutes, and then hit "Re-sync all data" in the top right menu. Let me know if this helps at all.
![image](https://user-images.githubusercontent.com/858456/204671137-a2e00bd6-bcdd-4031-af08-992492805d92.png)

The Sentry error is from my automatic error reporting system, which is currently down due to a server migration (restoring that one wasn't a major priority for me :wink:) The errors won't be affecting KanjiSchool at all, and shouldn't be affecting browser performance either, but I will try to restore the service soon to clear them away.

**Comment by MartiiDev** [comment]
Oh I tried re-syncing again and it worked! I did it yesterday and nothing had changed...
I didn't know there was an automatic error reporting system, might as well use this if I have some projects in the future.
